// 组件状态
export const ADD_KEEPALIVE = 'ADD_KEEPALIVE'  
export const DEL_KEEPALIVE = 'DEL_KEEPALIVE'

export const ADD_SECKEEPALIVE = 'ADD_SECKEEPALIVE'
export const DEL_SECKEEPALIVE = 'DEL_SECKEEPALIVE'
export const LOGIN_STATUS = 'LOGIN_STATUS'
export const SET_SHELF_DATA = 'SET_SHELF_DATA'
