let data = [
    {
        qcGroupStr: 123213,
        qcStandNo: 132,
        qcStandName: "大哈吉斯",
        propertyNo: "打哈萨克",
        qcStandTypeStr: "asdasd",
        sourcePosition: "深圳~深度克隆附近",
        waitGroupPosition: "asdasd",
        gbPallet: "打哈萨克",
        createUserName: "asdasdasd",
        createTime: "asd打哈萨克asdasd",
        updateUserName: "asdasdasd",
        updateTime: "2019-10-2",
    },
    {
        qcGroupStr: 123213,
        qcStandNo: 132,
        qcStandName: "大哈吉斯",
        propertyNo: "打哈萨克",
        qcStandTypeStr: "asdasd",
        sourcePosition: "深圳~深度克隆附近",
        waitGroupPosition: "asdasd",
        gbPallet: "asdasdasd",
        createUserName: "打哈萨克",
        createTime: "asdasdasd",
        updateUserName: "打哈萨克",
        updateTime: "2019-10-2",
    },
    {
        qcGroupStr: 123213,
        qcStandNo: 132,
        qcStandName: "大哈吉斯",
        propertyNo: "打哈萨克",
        qcStandTypeStr: "asdasd",
        sourcePosition: "深圳~深度克隆附近",
        waitGroupPosition: "asdasd",
        gbPallet: "asdasdasd",
        createUserName: "打哈萨克",
        createTime: "asdasdasd",
        updateUserName: "打哈萨克",
        updateTime: "2019-10-2",
    },
    {
        qcGroupStr: 123213,
        qcStandNo: 132,
        qcStandName: "大哈吉斯",
        propertyNo: "打哈萨克",
        qcStandTypeStr: "asdasd",
        sourcePosition: "深圳~深度克隆附近",
        waitGroupPosition: "asdasd",
        gbPallet: "打哈萨克",
        createUserName: "asdasdasd",
        createTime: "打哈萨克",
        updateUserName: "asdasdasd",
        updateTime: "2019-10-2",
    },
    {
        qcGroupStr: 123213,
        qcStandNo: 132,
        qcStandName: "大哈吉斯",
        propertyNo: "打哈萨克",
        qcStandTypeStr: "asdasd",
        sourcePosition: "深圳~深度克隆附近",
        waitGroupPosition: "asdasd",
        gbPallet: "asdasdasd",
        createUserName: "打哈萨克",
        createTime: "asdasdasd",
        updateUserName: "打哈萨克",
        updateTime: "2019-10-2",
    },
]
export { data }